import { notFound } from "next/navigation";
import { api } from "@/lib/api";
import { compactUnit, formatNumber, formatRelative } from "@/lib/format";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { CopyLinkButton } from "@/components/copy-link-button";
import { RerunLink } from "@/components/rerun-link";
import { StatusTooltip } from "@/components/status-tooltip";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

export const dynamic = "force-dynamic";

export default async function RunDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const runId = Number(id);
  if (!Number.isFinite(runId)) notFound();

  const run = await api.getRun(runId).catch(() => null);
  if (!run) notFound();

  const aiSummary = await api.getRunSummary(runId).catch(() => null);

  return (
    <div className="space-y-8 animate-fade-in-up">
      {/* Header */}
      <section className="flex flex-wrap items-start justify-between gap-4 border-b border-border/60 pb-6">
        <div className="space-y-1">
          <h1 className="font-mono text-lg font-semibold leading-tight">{run.config_name}</h1>
          <p className="text-[13px] text-muted-foreground">
            concurrency{" "}
            <span className="tabular-numbers text-foreground/80">
              {run.concurrency.toLocaleString()}
            </span>{" "}
            · {formatRelative(run.started_at)}
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-1.5">
          <Badge variant="outline" className="font-mono lowercase">{run.trigger}</Badge>
          <StatusTooltip status={run.status} extraNote={run.failure_reason}>
            <Badge
              variant={
                run.status === "passed"
                  ? "success"
                  : run.status === "partial"
                    ? "warning"
                    : "destructive"
              }
            >
              <span
                className={`inline-block h-1.5 w-1.5 rounded-full ${
                  run.status === "passed"
                    ? "bg-success"
                    : run.status === "partial"
                      ? "bg-warning"
                      : "bg-destructive"
                }`}
                aria-hidden
              />
              {run.status}
            </Badge>
          </StatusTooltip>
          <RerunLink prNumber={run.pr_number} configName={run.config_name} />
          <CopyLinkButton />
        </div>
      </section>

      {/* Failure banner (failed or partial runs) */}
      {(run.status === "failed" || run.status === "partial") && (
        <section
          className={`rounded-xl border p-4 ${
            run.status === "failed"
              ? "border-destructive/40 bg-destructive/5"
              : "border-warning/40 bg-warning/5"
          }`}
        >
          <p
            className={`text-[13px] font-semibold ${
              run.status === "failed" ? "text-destructive" : "text-warning"
            }`}
          >
            {run.status === "failed"
              ? "This run failed"
              : "Partial run — some concurrencies missing"}
          </p>
          <p className="mt-1 text-[12px] text-muted-foreground">
            {run.failure_reason ?? "No reason recorded."} Reconciled from the
            expected matrix — no benchmark output was uploaded for this
            (config, concurrency) pair.
          </p>
          <div className="mt-2 flex gap-3 text-[12px]">
            <a
              className="text-primary transition hover:underline"
              href={run.gh_job_url ?? run.github_run_url}
              target="_blank"
              rel="noreferrer"
            >
              View GitHub Actions logs →
            </a>
          </div>
        </section>
      )}

      {/* AI log analysis (generated by analyze_logs_with_modal.py on failures) */}
      {aiSummary && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-baseline justify-between gap-3">
              <span className="text-[13px] font-semibold uppercase tracking-[0.08em] text-muted-foreground">
                AI log analysis
              </span>
              <span className="text-[11px] font-normal normal-case tracking-normal text-muted-foreground/70">
                generated {formatRelative(aiSummary.generated_at)}
                {aiSummary.model && (
                  <>
                    <span className="mx-1 text-muted-foreground/60">·</span>
                    <span className="font-mono">{aiSummary.model}</span>
                  </>
                )}
              </span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="prose prose-sm prose-neutral max-w-none dark:prose-invert prose-headings:font-semibold prose-headings:text-foreground prose-p:text-foreground/90 prose-strong:text-foreground prose-code:rounded prose-code:bg-muted prose-code:px-1 prose-code:py-0.5 prose-code:text-[12px] prose-code:before:content-none prose-code:after:content-none prose-pre:bg-muted/50 prose-pre:text-[12px]">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {aiSummary.body}
              </ReactMarkdown>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Two-column meta */}
      <section className="grid gap-4 md:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Commit</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 text-[13px]">
            <div className="flex items-center gap-2">
              <span className="w-20 shrink-0 text-[11px] uppercase tracking-wider text-muted-foreground">
                SHA
              </span>
              {run.commit_sha ? (
                <a
                  className="font-mono text-primary transition hover:underline"
                  href={`https://github.com/sgl-project/sglang/commit/${run.commit_sha}`}
                  target="_blank"
                  rel="noreferrer"
                >
                  {run.commit_short_sha ?? run.commit_sha.slice(0, 7)}
                </a>
              ) : (
                <span className="text-muted-foreground">—</span>
              )}
            </div>
            {run.commit_message && (
              <p className="line-clamp-2 text-foreground/80">
                {run.commit_message.split("\n")[0]}
              </p>
            )}
            <div className="flex flex-wrap gap-x-3 gap-y-1 text-[12px] text-muted-foreground">
              <span>{run.commit_author ?? "unknown author"}</span>
              <span>·</span>
              <span>{run.commit_date ? formatRelative(run.commit_date) : "—"}</span>
            </div>
            {run.pr_number && (
              <div className="pt-1 text-[12px]">
                <a
                  className="text-primary transition hover:underline"
                  href={`https://github.com/sgl-project/sglang/pull/${run.pr_number}`}
                  target="_blank"
                  rel="noreferrer"
                >
                  PR #{run.pr_number}
                </a>
                {run.pr_title && (
                  <span className="text-foreground/70"> · {run.pr_title}</span>
                )}
              </div>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Run</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2 text-[13px]">
            <KV label="GitHub Actions">
              <a
                className="text-primary transition hover:underline"
                href={run.github_run_url}
                target="_blank"
                rel="noreferrer"
              >
                <span className="font-mono">
                  {run.github_run_id}-{run.github_run_attempt}
                </span>
              </a>
            </KV>
            <KV label="Slurm job">
              <span className="font-mono text-foreground/80">{run.slurm_job_id ?? "—"}</span>
            </KV>
            <KV label="GPUs">
              <span className="font-mono tabular-numbers text-foreground/80">
                {run.num_gpus ?? "—"}
                <span className="mx-1.5 text-muted-foreground">·</span>
                prefill {run.prefill_gpus ?? "—"} / decode {run.decode_gpus ?? "—"}
              </span>
            </KV>
            <KV label="ISL / OSL">
              <span className="font-mono tabular-numbers text-foreground/80">
                {run.isl ?? "—"} / {run.osl ?? "—"}
              </span>
            </KV>
            <KV label="Logs">
              {run.s3_log_prefix ? (
                <a
                  className="break-all font-mono text-[11px] text-primary transition hover:underline"
                  href={`https://sgl-ci-logs-khjfeoysf.brevlab.com/browser/sglang-ci-logs/${encodeURIComponent(run.s3_log_prefix)}`}
                  target="_blank"
                  rel="noreferrer"
                >
                  {run.s3_log_prefix}
                </a>
              ) : (
                <span className="text-[11px] text-muted-foreground">
                  no logs uploaded
                </span>
              )}
            </KV>
          </CardContent>
        </Card>
      </section>

      {/* Metrics — hidden entirely for failed runs (no JSON, no metrics) */}
      {run.status !== "failed" && (
        <section className="space-y-3">
          <div className="flex items-baseline justify-between">
            <h2 className="text-[11px] font-semibold uppercase tracking-[0.08em] text-muted-foreground">
              Metrics
            </h2>
            <span className="text-[11px] text-muted-foreground/70">
              {run.metrics.length} captured
            </span>
          </div>
          {run.metrics.length === 0 ? (
            <Card>
              <CardContent className="py-10 text-center text-[13px] text-muted-foreground">
                No metrics parsed for this run.
              </CardContent>
            </Card>
          ) : (
            <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
              {run.metrics.map((m) => (
                <MetricCard key={m.name} name={m.name} value={m.value} unit={m.unit} />
              ))}
            </div>
          )}
        </section>
      )}
    </div>
  );
}

function KV({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex items-baseline gap-2">
      <span className="w-24 shrink-0 text-[11px] uppercase tracking-wider text-muted-foreground">
        {label}
      </span>
      <span className="min-w-0">{children}</span>
    </div>
  );
}

function MetricCard({
  name,
  value,
  unit,
}: {
  name: string;
  value: number;
  unit: string | null;
}) {
  return (
    <Card>
      <CardContent className="space-y-1 p-4">
        <p className="truncate font-mono text-[11px] uppercase tracking-wider text-muted-foreground">
          {name}
        </p>
        <p className="font-mono text-[17px] font-semibold tabular-numbers">
          {formatNumber(value)}
          {compactUnit(unit) && (
            <span className="ml-1 text-[12px] font-normal text-muted-foreground">
              {compactUnit(unit)}
            </span>
          )}
        </p>
      </CardContent>
    </Card>
  );
}
